### ISSUE TITLE
import deeplabcut fails

### ISSUE THREAD

**Issue by rckoepke** [MMathisLab/Docker4DeepLabCut2.0#19]
On a fresh installation I tried to run

```
rckoepke@f3a6434b8bd0:/home/rckoepke/DLC$ ipython
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
```

and received the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>()
----> 1 import deeplabcut

/usr/local/lib/python3.6/dist-packages/deeplabcut/__init__.py in <module>()
     28     else:
     29         mpl.use('Agg')
---> 30     from deeplabcut import generate_training_dataset
     31     from deeplabcut import refine_training_dataset
     32     from deeplabcut.generate_training_dataset import label_frames, dropannotationfileentriesduetodeletedimages, comparevideolistsanddatafolders, dropimagesduetolackofannotation

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/__init__.py in <module>()
     16     pass
     17 else:
---> 18     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
     19     from deeplabcut.generate_training_dataset.labeling_toolbox import *
     20     from deeplabcut.generate_training_dataset.multiple_individual_labeling_toolbox import *

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py in <module>()
     17 
     18 import numpy as np
---> 19 import wx
     20 
     21 class DraggablePoint:

ModuleNotFoundError: No module named 'wx'

```

running `rckoepke@f3a6434b8bd0:/home/rckoepke/DLC$ sudo apt install python-wxtools` did not fix the problem.

running `pip install wxPython` fails due to lack of gtk+:

```checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gtk+-3.0.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'gtk+-3.0' found
    Package gthread-2.0 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `gthread-2.0.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'gthread-2.0' found
    no
    *** Could not run GTK+ test program, checking why...
    *** The test program failed to compile or link. See the file config.log for the
    *** exact error that occured. This usually means GTK+ is incorrectly installed.
    configure: error:
    The development files for GTK+ were not found. For GTK+ 2, please
    ensure that pkg-config is in the path and that gtk+-2.0.pc is
    installed. For GTK+ 1.2 please check that gtk-config is in the path,
    and that the version is 1.2.3 or above. Also check that the
    libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config
    --libs' are in the LD_LIBRARY_PATH or equivalent.
    
    Error running configure
    ERROR: failed building wxWidgets
    Traceback (most recent call last):
      File "build.py", line 1468, in cmd_build_wx
        wxbuild.main(wxDir(), build_options)
      File "/tmp/pip-install-pkzt_vvx/wxPython/buildtools/build_wxwidgets.py", line 372, in main
        "Error running configure")
      File "/tmp/pip-install-pkzt_vvx/wxPython/buildtools/build_wxwidgets.py", line 85, in exitIfError
        raise builder.BuildError(msg)
    buildtools.builder.BuildError: Error running configure
    Finished command: build_wx (0m5.642s)
    Finished command: build (0m5.642s)
    Command '"/usr/bin/python3" -u build.py build' failed with exit code 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-pkzt_vvx/wxPython/setup.py'"'"'; __file__='"'"'/tmp/pip-install-pkzt_vvx/wxPython/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-xeznpt_e/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.
```

then tried `sudo apt install libgtk-3-dev`

after this, `pip install wxPython` fails at:

```
rckoepke@f3a6434b8bd0:/home/rckoepke/DLC$ pip install wxPython
Processing ./.cache/pip/wheels/7e/31/ff/0353a9b7a296b15b20a5300cb56da71c3018930c777f3b3b21/wxPython-4.0.7.post2-cp36-cp36m-linux_x86_64.whl
Requirement already satisfied: pillow in /usr/local/lib/python3.6/dist-packages (from wxPython) (5.0.0)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from wxPython) (1.11.0)
Requirement already satisfied: numpy; python_version >= "3.0" in /usr/local/lib/python3.6/dist-packages (from wxPython) (1.17.4)
Installing collected packages: wxPython
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/wxPython-4.0.7.post2.dist-info'
Consider using the `--user` option or check the permissions.
```

but `sudo pip install wxPython` succeeds (warning to passersby, this is almost certainly the WRONG way to "do it")

at this point, trying `In [1]: import deeplabcut` results in the following:

```
rckoepke@f3a6434b8bd0:/home/rckoepke/DLC$ ipython
Python 3.6.3 (default, Oct  6 2017, 08:44:35) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import deeplabcut
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/usr/lib/python3.6/tkinter/__init__.py in <module>()
     36 try:
---> 37     import _tkinter
     38 except ImportError as msg:

ModuleNotFoundError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>()
----> 1 import deeplabcut

/usr/local/lib/python3.6/dist-packages/deeplabcut/__init__.py in <module>()
     28     else:
     29         mpl.use('Agg')
---> 30     from deeplabcut import generate_training_dataset
     31     from deeplabcut import refine_training_dataset
     32     from deeplabcut.generate_training_dataset import label_frames, dropannotationfileentriesduetodeletedimages, comparevideolistsanddatafolders, dropimagesduetolackofannotation

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/__init__.py in <module>()
     17 else:
     18     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
---> 19     from deeplabcut.generate_training_dataset.labeling_toolbox import *
     20     from deeplabcut.generate_training_dataset.multiple_individual_labeling_toolbox import *
     21     from deeplabcut.generate_training_dataset.frame_extraction_toolbox import *

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py in <module>()
     25 import argparse
     26 from deeplabcut.generate_training_dataset import auxfun_drag_label
---> 27 from deeplabcut.utils import auxiliaryfunctions
     28 from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
     29 from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg as NavigationToolbar

/usr/local/lib/python3.6/dist-packages/deeplabcut/utils/__init__.py in <module>()
----> 1 from deeplabcut.utils.make_labeled_video import *
      2 from deeplabcut.utils.auxiliaryfunctions import *
      3 from deeplabcut.utils.video_processor import *
      4 from deeplabcut.utils.plotting import *
      5 

/usr/local/lib/python3.6/dist-packages/deeplabcut/utils/make_labeled_video.py in <module>()
     32     mpl.use('WxAgg') #TkAgg
     33 else:
---> 34     mpl.use('TkAgg')
     35 import matplotlib.pyplot as plt
     36 

/usr/local/lib/python3.6/dist-packages/matplotlib/__init__.py in use(arg, warn, force)
   1389         if force:
   1390             from matplotlib.pyplot import switch_backend
-> 1391             switch_backend(name)
   1392     # Finally if pyplot is not imported update both rcParams and
   1393     # rcDefaults so restoring the defaults later with rcdefaults

/usr/local/lib/python3.6/dist-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    205         else "matplotlib.backends.backend_{}".format(newbackend.lower()))
    206 
--> 207     backend_mod = importlib.import_module(backend_name)
    208     Backend = type(
    209         "Backend", (matplotlib.backends._Backend,), vars(backend_mod))

/usr/lib/python3.6/importlib/__init__.py in import_module(name, package)
    124                 break
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 
    128 

/usr/local/lib/python3.6/dist-packages/matplotlib/backends/backend_tkagg.py in <module>()
----> 1 from . import _backend_tk
      2 from .backend_agg import FigureCanvasAgg
      3 from ._backend_tk import (
      4     _BackendTk, FigureCanvasTk, FigureManagerTk, NavigationToolbar2Tk)
      5 

/usr/local/lib/python3.6/dist-packages/matplotlib/backends/_backend_tk.py in <module>()
      3 import os.path
      4 import sys
----> 5 import tkinter as Tk
      6 from tkinter.simpledialog import SimpleDialog
      7 from contextlib import contextmanager

/usr/lib/python3.6/tkinter/__init__.py in <module>()
     37     import _tkinter
     38 except ImportError as msg:
---> 39     raise ImportError(str(msg) + ', please install the python3-tk package')
     40 TclError = _tkinter.TclError
     41 from tkinter.constants import *

ImportError: No module named '_tkinter', please install the python3-tk package

In [2]: exit
```

this is fixed with `sudo apt install python3-tk` and finally:

`In [1]: import deeplabcut` works without failing.

**Comment by MMathisLab** [comment]
the GUI does not work in the main Docker I provide, i.e. you need to export DLClight=True before starting ipython then importing
