### ISSUE TITLE
Import Tensorflow Failed due to missing libcuda.so.1 file

### ISSUE THREAD

**Issue by stbjelcevic** [MMathisLab/Docker4DeepLabCut2.0#22]
I was able to successfully build the docker image and run the container. However, when I try to import deeplabcut to check my installation, I get the following error:

stefan@d3f3c94e1afa:/$ cd home/
stefan@d3f3c94e1afa:/home$ export DLClight=True
stefan@d3f3c94e1afa:/home$ ipython
Python 3.6.3 (default, Oct  6 2017, 08:44:35)
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import deeplabcut
DLC loaded in light mode; you cannot use any GUI (labeling, relabeling and standalone GUI)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__
/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper
/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:
/usr/lib/python3.6/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:
/usr/lib/python3.6/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
During handling of the above exception, another exception occurred:
ImportError                               Traceback (most recent call last)
<ipython-input-1-cfa4f159dfc5> in <module>()
----> 1 import deeplabcut
/usr/local/lib/python3.6/dist-packages/deeplabcut/__init__.py in <module>()
     41     print("Project loaded in colab-mode. Apparently Colab has trouble loading statsmodels, so the smoothing & outlier frame extraction is disabled. Sorry!")
     42 else:
---> 43     from deeplabcut.refine_training_dataset import extract_outlier_frames, merge_datasets
     44     from deeplabcut.post_processing import filterpredictions, analyzeskeleton
     45
/usr/local/lib/python3.6/dist-packages/deeplabcut/refine_training_dataset/__init__.py in <module>()
     18     from deeplabcut.refine_training_dataset.auxfun_drag import *
     19
---> 20 from deeplabcut.refine_training_dataset.outlier_frames import *
/usr/local/lib/python3.6/dist-packages/deeplabcut/refine_training_dataset/outlier_frames.py in <module>()
     15 import pandas as pd
     16 import statsmodels.api as sm
---> 17 from deeplabcut.utils import auxiliaryfunctions, visualization
     18 from deeplabcut.utils import frameselectiontools
     19 import argparse
/usr/local/lib/python3.6/dist-packages/deeplabcut/utils/__init__.py in <module>()
----> 1 from deeplabcut.utils.make_labeled_video import *
      2 from deeplabcut.utils.auxiliaryfunctions import *
      3 from deeplabcut.utils.video_processor import *
      4 from deeplabcut.utils.plotting import *
      5
/usr/local/lib/python3.6/dist-packages/deeplabcut/utils/make_labeled_video.py in <module>()
     36
     37 from deeplabcut.utils import auxiliaryfunctions
---> 38 from deeplabcut.pose_estimation_tensorflow.config import load_config
     39 from skimage.util import img_as_ubyte
     40 from skimage.draw import circle_perimeter, circle, line,line_aa
/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/__init__.py in <module>()
     11 from deeplabcut.pose_estimation_tensorflow.dataset import *
     12 from deeplabcut.pose_estimation_tensorflow.models import *
---> 13 from deeplabcut.pose_estimation_tensorflow.nnet import *
     14 from deeplabcut.pose_estimation_tensorflow.util import *
     15
/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/__init__.py in <module>()
     12
     13 """
---> 14 from deeplabcut.pose_estimation_tensorflow.nnet.losses import *
     15 from deeplabcut.pose_estimation_tensorflow.nnet.net_factory import *
     16 from deeplabcut.pose_estimation_tensorflow.nnet.pose_net import *
/usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/nnet/losses.py in <module>()
      3 https://github.com/eldar/pose-tensorflow
      4 '''
----> 5 import tensorflow as tf
      6 vers = (tf.__version__).split('.')
      7 if int(vers[0])==1 and int(vers[1])>12:
/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py in <module>()
     22
     23 # pylint: disable=g-bad-import-order
---> 24 from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
     25 # pylint: disable=wildcard-import
     26 from tensorflow.tools.api.generator.api import *  # pylint: disable=redefined-builtin
/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48
---> 49 from tensorflow.python import pywrap_tensorflow
     50
     51 # Protocol buffers
/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/usr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

Could this be a problem with my cuda installation on my host machine? I have cuda 10 on my host machine and it looks like this container uses cuda 9.

**Comment by stbjelcevic** [comment]
Solved! Since I am using docker 19.03 and not nvidia-docker 2, I had to update the dlc-docker file and set NV_DOCKER_ARGS="--gpus all" in order to get the shared object in the container.

I am now getting the ModuleNotFoundError: No module named 'wx' error, but I think I saw another thread where that was resolved.
